

#
# Your backpack configuration
#
version: 1

# projects_external:
# - name: community
#   href: https://....
#
# set up projects as convenient shortcuts to your starter projects or templates.
# $ backpack new rust-starter
#
# projects:
#   rust-starter: 
#     shortlink: jondot/rust-starter  # you can use any custom prefix here too
#     mode: new
#   rust-ci: 
#     shortlink: jondot/rust-starter/-/.github  # you can use any custom prefix here too
#     mode: apply
#   react: 
#     shortlink: foobar  # you can use any custom prefix here too
#
#
projects:
  react-prompts:
    shortlink: kriasoft/react-starter-kit
    actions:
    - name: "name of file"
      hook: before
      interaction:
        kind: input
        prompt: name of your app
        out: file_name
    swaps:
    - key: README.md
      val_template: "{{file_name}}"
      path: .*
    - key: tsconfig.json
      val: ts-config.json

##
# set up custom vendor prefixes, for convenience and also for custom git
# URLs such as hosted github or gitlab and others.
# $ backpack new ghe:jondot/rust-starter
#
# vendors:
#   # overrides the default git vendor when you don't specify a prefix.
#   # $ backpack my-org/my-repo
#   default: 
#     kind: gitlab # options: gitlab | github | bitbucket
#     base: my.gitlab.com
#   custom:
#     # custom github org to prefix, and also overrides the 'gh:' prefix.
#     # $ backpack new gh:my-repo my-repo
#     gh:
#       kind: github
#       base: github.com/my-org
#
#     # sets the 'ghe' prefix to a custom git vendor for your organization, self-hosted.
#     # $ backpack new ghe:my-team/my-repo my-repo
#     ghe:
#       kind: github
#       base: github.enterprise.example.com
